### ISSUE TITLE
Unable to add DynamicConsoleLogger to Console application

### ISSUE THREAD

**Issue by VenkateshSrini** [SteeltoeOSS/Logging#3]
Hi,
Unlike the usual web application in ASP.NET core, We have console application (.NET core) hosted in PCF. These application are deployed and stopped. They are either invoked using PCF scheduler or using CF task. Now the problem is, Even after adding the DynamicLoggerConsole, the dynamic logging is not getting enabled in PCF.

We do not need management endpoints for this hence we have not added the management actuators for the same.

**Comment by TimHess** [comment]
Anything logged to Console (stdout) should show up, whether you use Console.WriteLine, or add the Microsoft ConsoleLogger or Steeltoe Dynamic Console Logger to Microsoft Logging. If you're not using the Logging actuator or needing to change log levels while the app is running, you probably don't need to use the Steeltoe logger at all.

Do you see output if your app does straight `Console.WriteLine("some text here");` ?

**Comment by jkonicki** [comment]
Closing issue.  Reopen if this is still a problem.

**Comment by VenkateshSrini** [comment]
@TimHess,

The point is I'm unable to change the logging level using the Pivotal UI inspite of  using actuator. Point to note is that it is not an Long running process. The whole app is invoked using a CF task. In normal condition the app is always in stopped state only.

**Comment by TimHess** [comment]
When running with `cf run-task` your doesn't get a port assigned (at least as far as I know - the 2.1.1 release of Steeltoe included some alterations to work around the port environment variable not being set, and we've seen issues with port binding failing when running that way), so I don't think there's a way to communicate with that instance of it
